Repository michelin/suricate, pull requests merged in 2018-10, with the labels that each got.

#345 Improve pom.xml & package.json
  package.json
  pom.xml
Labels: bug, intermediate

#344 Bump to Springboot 2.0.5 and remove already defined dependencies
  pom.xml
Labels: backend, beginner, dependencies

#346 Improve Swagger annotations & generate swagger.json
  pom.xml
  src/main/java/io/suricate/monitoring/controllers/api/ConfigurationController.java
  src/main/java/io/suricate/monitoring/controllers/api/ProjectController.java
  src/main/java/io/suricate/monitoring/controllers/api/RepositoryController.java
  src/main/java/io/suricate/monitoring/controllers/api/SettingController.java
  src/main/java/io/suricate/monitoring/controllers/api/UserController.java
  src/main/java/io/suricate/monitoring/model/dto/LibraryDto.java
  src/main/java/io/suricate/monitoring/model/dto/project/ProjectDto.java
  src/main/java/io/suricate/monitoring/model/dto/setting/SettingDto.java
  src/main/java/io/suricate/monitoring/model/dto/user/RoleDto.java
  src/main/java/io/suricate/monitoring/model/dto/user/UserDto.java
  src/main/java/io/suricate/monitoring/model/dto/widget/CategoryDto.java
  src/main/java/io/suricate/monitoring/model/dto/widget/WidgetDto.java
  src/main/java/io/suricate/monitoring/model/dto/widget/WidgetParamDto.java
Labels: backend, beginner, documentation

#348 Add Azure Pipeline badge
  README.md
Labels: documentation, enhancement

#349 Add more option for LDAP security
  src/main/java/io/suricate/monitoring/configuration/ApplicationProperties.java
  src/main/java/io/suricate/monitoring/configuration/security/ldap/LdapAuthentication.java
  src/main/resources/application.yml
Labels: backend, enhancement, expert

#358 Fix bug when creating first dashboard
  src/main/webapp/app/modules/dashboard/dashboard.service.ts
Labels: beginner, bug, frontend

#361 Update info for release
  pom.xml
Labels: backend, frontend

#364 Init new version
  pom.xml
Labels: backend, beginner

#366 Add proxy set up on startup
  src/main/java/io/suricate/monitoring/BackendApplication.java
  src/main/java/io/suricate/monitoring/configuration/ProxyConfiguration.java
  src/main/java/io/suricate/monitoring/utils/MonitorProxySelector.java
Labels: backend, beginner, enhancement

#368 Clear cache when setting configuration
  src/main/java/io/suricate/monitoring/controllers/api/ConfigurationController.java
Labels: backend, beginner, bug

#369 Add a generic profil based on env vars
  .gitignore
  src/main/java/io/suricate/monitoring/service/api/ConfigurationService.java
  src/main/resources/application-docker.yml
  src/main/resources/application-generic.yml
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/webapp/environments/environment.local.ts
  src/main/webapp/environments/environment.prod.ts
  yarn.lock
Labels: backend, intermediate, new feature

#370 Init clevercloud deployment
  clevercloud/war.json
Labels: enhancement, intermediate
