Repository michelin/suricate, pull requests merged in 2019-02, with the labels that each got.

#411 #410 - Fix edit dashboard issue
  src/main/webapp/app/home/components/add-dashboard-dialog/add-dashboard-dialog.component.ts
  src/main/webapp/app/layout/header/components/dashboard-actions/dashboard-actions.component.ts
  src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.html
Labels: beginner, bug, frontend

#425 #424 - Encrypt global configurations with password type when editing …
  src/main/java/io/suricate/monitoring/service/api/ProjectWidgetService.java
  src/main/java/io/suricate/monitoring/service/api/WidgetService.java
  src/main/java/io/suricate/monitoring/service/mapper/ProjectWidgetMapper.java
Labels: backend, beginner, bug, security

#427 #426 - Unable users to add/edit widget
  src/main/java/io/suricate/monitoring/controllers/api/CategoryController.java
Labels: backend, beginner, bug

#429 #428 - Delete AdminGuard for widget list page
  src/main/webapp/app/modules/widget/widget.route.ts
Labels: beginner, bug, frontend

#431 430 improve the dashboard screen css
  src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen-widget.component.scss
  src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.scss
  src/main/webapp/sass/_dashboard-screen.scss
  src/main/webapp/sass/_global-styles.scss
  src/main/webapp/sass/styles.scss
Labels: beginner, enhancement, frontend

#433 #432 - Fix widget grid position
  src/main/java/io/suricate/monitoring/model/entity/project/Project.java
Labels: backend, beginner, bug, enhancement

#435 #434 - Fix collision when moving widget with small height
  src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.ts
Labels: beginner, bug, frontend

#437 Feature/436 manage security on dashboards
  src/main/java/io/suricate/monitoring/controllers/api/ProjectController.java
  src/main/java/io/suricate/monitoring/controllers/api/ProjectWidgetController.java
  src/main/java/io/suricate/monitoring/service/api/ProjectService.java
  src/main/java/io/suricate/monitoring/utils/SecurityUtils.java
  src/main/webapp/app/home/components/add-dashboard-dialog/add-dashboard-dialog.component.html
  src/main/webapp/app/layout/header/components/dashboard-actions/dashboard-actions.component.html
  src/main/webapp/app/layout/header/components/dashboard-actions/dashboard-actions.component.ts
  src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.html
  src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.ts
  src/main/webapp/app/modules/dashboard/dashboard.service.ts
  src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.html
  src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.ts
Labels: backend, frontend, intermediate, new feature, security

#439 #438 - Delete dashboard frontend management
  src/main/java/io/suricate/monitoring/controllers/api/ProjectController.java
  src/main/java/io/suricate/monitoring/service/api/ProjectService.java
  src/main/webapp/app/home/components/add-dashboard-dialog/add-dashboard-dialog.component.ts
  src/main/webapp/app/layout/header/components/dashboard-actions/dashboard-actions.component.html
  src/main/webapp/app/layout/header/components/dashboard-actions/dashboard-actions.component.ts
  src/main/webapp/app/modules/dashboard/components/dashboard-screen/dashboard-screen.component.ts
  src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.ts
  src/main/webapp/assets/i18n/en.json
Labels: backend, beginner, frontend, new feature

#441 #440 - Inject Global configurations in mustache template if already done
  src/main/java/io/suricate/monitoring/service/api/ConfigurationService.java
  src/main/java/io/suricate/monitoring/service/api/ProjectWidgetService.java
Labels: backend, beginner, bug

#445 #444 - Open a new tab when click on TV icon in the sidenav
  src/main/webapp/app/layout/sidenav/pages/sidenav.component.html
Labels: beginner, frontend, ui / ux

#443 Feature/442 sidenav profil arrow with white color
  src/main/webapp/sass/components/material/_mat-sidenav-theme.scss
Labels: beginner, frontend, ui / ux

#451 Init 2.1
  package.json
  pom.xml
Labels: backend, beginner, frontend

#457 452 be able to have clickable cards on widget creation modal
  src/main/webapp/app/home/home.component.html
  src/main/webapp/app/home/home.component.scss
  src/main/webapp/app/layout/header/components/add-widget-dialog/add-widget-dialog.component.html
  src/main/webapp/app/layout/header/components/add-widget-dialog/add-widget-dialog.component.scss
  src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.html
  src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.scss
  src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.ts
  src/main/webapp/app/shared/components/toast/toast.component.ts
  src/main/webapp/sass/components/material/_mat-card-theme.scss
Labels: beginner, enhancement, frontend, ui / ux

#458 Bugfix/viewresolver
  angular.json
  pom.xml
  src/main/resources/application-h2.yml
  src/main/resources/application.yml
  yarn.lock
Labels: bug, frontend, intermediate

#459 Feature/clevercloud deploy
  clevercloud/maven.json
  clevercloud/war.json
Labels: backend, enhancement, intermediate

#461 #460 - Fix h2 types error
  src/main/resources/application-generic.yml
  src/main/resources/application-h2.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/h2db/V1_2_1__fix_column_types.sql
Labels: backend, bug, intermediate

#466 #464 - Fix issue on card
  pom.xml
  src/main/webapp/app/home/home.component.html
  src/main/webapp/app/home/home.component.scss
  src/main/webapp/app/layout/header/components/add-widget-dialog/add-widget-dialog.component.html
  src/main/webapp/app/layout/header/components/add-widget-dialog/add-widget-dialog.component.scss
  src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.html
  src/main/webapp/app/modules/dashboard/pages/dashboard-detail/dashboard-detail.component.scss
  src/main/webapp/sass/_global-styles.scss
  src/main/webapp/sass/components/material/_mat-card-theme.scss
Labels: beginner, bug, frontend
